// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum AppClipAction: String, Codable, CaseIterable {
    case `open` = "OPEN"
    case view = "VIEW"
    case play = "PLAY"
}
