// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum BundleIDPlatform: String, Codable, CaseIterable {
    case ios = "IOS"
    case macOs = "MAC_OS"
}
