// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum CiExecutionProgress: String, Codable, CaseIterable {
    case pending = "PENDING"
    case running = "RUNNING"
    case complete = "COMPLETE"
}
