// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum CiGitRefKind: String, Codable, CaseIterable {
    case branch = "BRANCH"
    case tag = "TAG"
}
