// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum MetricCategory: String, Codable, CaseIterable {
    case hang = "HANG"
    case launch = "LAUNCH"
    case memory = "MEMORY"
    case disk = "DISK"
    case battery = "BATTERY"
    case termination = "TERMINATION"
    case animation = "ANIMATION"
}
