// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionOfferCodeCustomCodes: SubscriptionOfferCodeCustomCodes {
        SubscriptionOfferCodeCustomCodes(path: path + "/subscriptionOfferCodeCustomCodes")
    }

    public struct SubscriptionOfferCodeCustomCodes {
        /// Path: `/v1/subscriptionOfferCodeCustomCodes`
        public let path: String

        public func post(_ body: API.SubscriptionOfferCodeCustomCodeCreateRequest) -> Request<API.SubscriptionOfferCodeCustomCodeResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionOfferCodeCustomCodes-create_instance")
        }
    }
}
