// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var appPreviews: AppPreviews {
        AppPreviews(path: path + "/appPreviews")
    }

    public struct AppPreviews {
        /// Path: `/v1/appPreviews`
        public let path: String

        public func post(_ body: API.AppPreviewCreateRequest) -> Request<API.AppPreviewResponse> {
            Request(path: path, method: "POST", body: body, id: "appPreviews-create_instance")
        }
    }
}
