// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var appClipAppStoreReviewDetails: AppClipAppStoreReviewDetails {
        AppClipAppStoreReviewDetails(path: path + "/appClipAppStoreReviewDetails")
    }

    public struct AppClipAppStoreReviewDetails {
        /// Path: `/v1/appClipAppStoreReviewDetails`
        public let path: String

        public func post(_ body: API.AppClipAppStoreReviewDetailCreateRequest) -> Request<API.AppClipAppStoreReviewDetailResponse> {
            Request(path: path, method: "POST", body: body, id: "appClipAppStoreReviewDetails-create_instance")
        }
    }
}
