// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var appEncryptionDeclarationDocuments: AppEncryptionDeclarationDocuments {
        AppEncryptionDeclarationDocuments(path: path + "/appEncryptionDeclarationDocuments")
    }

    public struct AppEncryptionDeclarationDocuments {
        /// Path: `/v1/appEncryptionDeclarationDocuments`
        public let path: String

        public func post(_ body: API.AppEncryptionDeclarationDocumentCreateRequest) -> Request<API.AppEncryptionDeclarationDocumentResponse> {
            Request(path: path, method: "POST", body: body, id: "appEncryptionDeclarationDocuments-create_instance")
        }
    }
}
