// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var inAppPurchaseSubmissions: InAppPurchaseSubmissions {
        InAppPurchaseSubmissions(path: path + "/inAppPurchaseSubmissions")
    }

    public struct InAppPurchaseSubmissions {
        /// Path: `/v1/inAppPurchaseSubmissions`
        public let path: String

        public func post(_ body: API.InAppPurchaseSubmissionCreateRequest) -> Request<API.InAppPurchaseSubmissionResponse> {
            Request(path: path, method: "POST", body: body, id: "inAppPurchaseSubmissions-create_instance")
        }
    }
}
