// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var inAppPurchaseLocalizations: InAppPurchaseLocalizations {
        InAppPurchaseLocalizations(path: path + "/inAppPurchaseLocalizations")
    }

    public struct InAppPurchaseLocalizations {
        /// Path: `/v1/inAppPurchaseLocalizations`
        public let path: String

        public func post(_ body: API.InAppPurchaseLocalizationCreateRequest) -> Request<API.InAppPurchaseLocalizationResponse> {
            Request(path: path, method: "POST", body: body, id: "inAppPurchaseLocalizations-create_instance")
        }
    }
}
