// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var reviewSubmissionItems: ReviewSubmissionItems {
        ReviewSubmissionItems(path: path + "/reviewSubmissionItems")
    }

    public struct ReviewSubmissionItems {
        /// Path: `/v1/reviewSubmissionItems`
        public let path: String

        public func post(_ body: API.ReviewSubmissionItemCreateRequest) -> Request<API.ReviewSubmissionItemResponse> {
            Request(path: path, method: "POST", body: body, id: "reviewSubmissionItems-create_instance")
        }
    }
}
