// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1.Builds.WithID.Relationships {
    public var individualTesters: IndividualTesters {
        IndividualTesters(path: path + "/individualTesters")
    }

    public struct IndividualTesters {
        /// Path: `/v1/builds/{id}/relationships/individualTesters`
        public let path: String

        public func get(limit: Int? = nil) -> Request<API.BuildIndividualTestersLinkagesResponse> {
            Request(path: path, method: "GET", query: makeGetQuery(limit), id: "builds-individualTesters-get_to_many_relationship")
        }

        private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(limit, forKey: "limit")
            return encoder.items
        }

        public func post(_ body: API.BuildIndividualTestersLinkagesRequest) -> Request<Void> {
            Request(path: path, method: "POST", body: body, id: "builds-individualTesters-create_to_many_relationship")
        }

        public func delete(_ body: API.BuildIndividualTestersLinkagesRequest) -> Request<Void> {
            Request(path: path, method: "DELETE", body: body, id: "builds-individualTesters-delete_to_many_relationship")
        }
    }
}
