// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1.AppStoreVersionPhasedReleases {
    public func id(_ id: String) -> WithID {
        WithID(path: "\(path)/\(id)")
    }

    public struct WithID {
        /// Path: `/v1/appStoreVersionPhasedReleases/{id}`
        public let path: String

        public func patch(_ body: API.AppStoreVersionPhasedReleaseUpdateRequest) -> Request<API.AppStoreVersionPhasedReleaseResponse> {
            Request(path: path, method: "PATCH", body: body, id: "appStoreVersionPhasedReleases-update_instance")
        }

        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "appStoreVersionPhasedReleases-delete_instance")
        }
    }
}
