// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1.AppEncryptionDeclarations.WithID.Relationships {
    public var builds: Builds {
        Builds(path: path + "/builds")
    }

    public struct Builds {
        /// Path: `/v1/appEncryptionDeclarations/{id}/relationships/builds`
        public let path: String

        public func post(_ body: API.AppEncryptionDeclarationBuildsLinkagesRequest) -> Request<Void> {
            Request(path: path, method: "POST", body: body, id: "appEncryptionDeclarations-builds-create_to_many_relationship")
        }
    }
}
