// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1.SubscriptionAvailabilities.WithID.Relationships {
    public var availableTerritories: AvailableTerritories {
        AvailableTerritories(path: path + "/availableTerritories")
    }

    public struct AvailableTerritories {
        /// Path: `/v1/subscriptionAvailabilities/{id}/relationships/availableTerritories`
        public let path: String
    }
}
