// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1.Apps.WithID.Relationships {
    public var appAvailability: AppAvailability {
        AppAvailability(path: path + "/appAvailability")
    }

    public struct AppAvailability {
        /// Path: `/v1/apps/{id}/relationships/appAvailability`
        public let path: String
    }
}
