// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var routingAppCoverages: RoutingAppCoverages {
        RoutingAppCoverages(path: path + "/routingAppCoverages")
    }

    public struct RoutingAppCoverages {
        /// Path: `/v1/routingAppCoverages`
        public let path: String

        public func post(_ body: API.RoutingAppCoverageCreateRequest) -> Request<API.RoutingAppCoverageResponse> {
            Request(path: path, method: "POST", body: body, id: "routingAppCoverages-create_instance")
        }
    }
}
