// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var appClipDefaultExperienceLocalizations: AppClipDefaultExperienceLocalizations {
        AppClipDefaultExperienceLocalizations(path: path + "/appClipDefaultExperienceLocalizations")
    }

    public struct AppClipDefaultExperienceLocalizations {
        /// Path: `/v1/appClipDefaultExperienceLocalizations`
        public let path: String

        public func post(_ body: API.AppClipDefaultExperienceLocalizationCreateRequest) -> Request<API.AppClipDefaultExperienceLocalizationResponse> {
            Request(path: path, method: "POST", body: body, id: "appClipDefaultExperienceLocalizations-create_instance")
        }
    }
}
