// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var inAppPurchasePriceSchedules: InAppPurchasePriceSchedules {
        InAppPurchasePriceSchedules(path: path + "/inAppPurchasePriceSchedules")
    }

    public struct InAppPurchasePriceSchedules {
        /// Path: `/v1/inAppPurchasePriceSchedules`
        public let path: String

        public func post(_ body: API.InAppPurchasePriceScheduleCreateRequest) -> Request<API.InAppPurchasePriceScheduleResponse> {
            Request(path: path, method: "POST", body: body, id: "inAppPurchasePriceSchedules-create_instance")
        }
    }
}
