// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionSubmissions: SubscriptionSubmissions {
        SubscriptionSubmissions(path: path + "/subscriptionSubmissions")
    }

    public struct SubscriptionSubmissions {
        /// Path: `/v1/subscriptionSubmissions`
        public let path: String

        public func post(_ body: API.SubscriptionSubmissionCreateRequest) -> Request<API.SubscriptionSubmissionResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionSubmissions-create_instance")
        }
    }
}
