// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionGroupSubmissions: SubscriptionGroupSubmissions {
        SubscriptionGroupSubmissions(path: path + "/subscriptionGroupSubmissions")
    }

    public struct SubscriptionGroupSubmissions {
        /// Path: `/v1/subscriptionGroupSubmissions`
        public let path: String

        public func post(_ body: API.SubscriptionGroupSubmissionCreateRequest) -> Request<API.SubscriptionGroupSubmissionResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionGroupSubmissions-create_instance")
        }
    }
}
