// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var betaTesterInvitations: BetaTesterInvitations {
        BetaTesterInvitations(path: path + "/betaTesterInvitations")
    }

    public struct BetaTesterInvitations {
        /// Path: `/v1/betaTesterInvitations`
        public let path: String

        public func post(_ body: API.BetaTesterInvitationCreateRequest) -> Request<API.BetaTesterInvitationResponse> {
            Request(path: path, method: "POST", body: body, id: "betaTesterInvitations-create_instance")
        }
    }
}
