// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var appInfoLocalizations: AppInfoLocalizations {
        AppInfoLocalizations(path: path + "/appInfoLocalizations")
    }

    public struct AppInfoLocalizations {
        /// Path: `/v1/appInfoLocalizations`
        public let path: String

        public func post(_ body: API.AppInfoLocalizationCreateRequest) -> Request<API.AppInfoLocalizationResponse> {
            Request(path: path, method: "POST", body: body, id: "appInfoLocalizations-create_instance")
        }
    }
}
