// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionGroups: SubscriptionGroups {
        SubscriptionGroups(path: path + "/subscriptionGroups")
    }

    public struct SubscriptionGroups {
        /// Path: `/v1/subscriptionGroups`
        public let path: String

        public func post(_ body: API.SubscriptionGroupCreateRequest) -> Request<API.SubscriptionGroupResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionGroups-create_instance")
        }
    }
}
