// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionGroupLocalizations: SubscriptionGroupLocalizations {
        SubscriptionGroupLocalizations(path: path + "/subscriptionGroupLocalizations")
    }

    public struct SubscriptionGroupLocalizations {
        /// Path: `/v1/subscriptionGroupLocalizations`
        public let path: String

        public func post(_ body: API.SubscriptionGroupLocalizationCreateRequest) -> Request<API.SubscriptionGroupLocalizationResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionGroupLocalizations-create_instance")
        }
    }
}
