// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.V1.ReviewSubmissionItems {
    public func id(_ id: String) -> WithID {
        WithID(path: "\(path)/\(id)")
    }

    public struct WithID {
        /// Path: `/v1/reviewSubmissionItems/{id}`
        public let path: String

        public func patch(_ body: API.ReviewSubmissionItemUpdateRequest) -> Request<API.ReviewSubmissionItemResponse> {
            Request(path: path, method: "PATCH", body: body, id: "reviewSubmissionItems-update_instance")
        }

        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "reviewSubmissionItems-delete_instance")
        }
    }
}
