// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var betaAppClipInvocations: BetaAppClipInvocations {
        BetaAppClipInvocations(path: path + "/betaAppClipInvocations")
    }

    public struct BetaAppClipInvocations {
        /// Path: `/v1/betaAppClipInvocations`
        public let path: String

        public func post(_ body: BetaAppClipInvocationCreateRequest) -> Request<BetaAppClipInvocationResponse> {
            Request(path: path, method: "POST", body: body, id: "betaAppClipInvocations-create_instance")
        }
    }
}
