// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1.AppClipDefaultExperiences.WithID.Relationships {
    public var releaseWithAppStoreVersion: ReleaseWithAppStoreVersion {
        ReleaseWithAppStoreVersion(path: path + "/releaseWithAppStoreVersion")
    }

    public struct ReleaseWithAppStoreVersion {
        /// Path: `/v1/appClipDefaultExperiences/{id}/relationships/releaseWithAppStoreVersion`
        public let path: String

        public var get: Request<AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponse> {
            Request(path: path, method: "GET", id: "appClipDefaultExperiences-releaseWithAppStoreVersion-get_to_one_relationship")
        }

        public func patch(_ body: AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest) -> Request<Void> {
            Request(path: path, method: "PATCH", body: body, id: "appClipDefaultExperiences-releaseWithAppStoreVersion-update_to_one_relationship")
        }
    }
}
