// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appStoreVersionPromotions: AppStoreVersionPromotions {
        AppStoreVersionPromotions(path: path + "/appStoreVersionPromotions")
    }

    public struct AppStoreVersionPromotions {
        /// Path: `/v1/appStoreVersionPromotions`
        public let path: String

        public func post(_ body: AppStoreVersionPromotionCreateRequest) -> Request<AppStoreVersionPromotionResponse> {
            Request(path: path, method: "POST", body: body, id: "appStoreVersionPromotions-create_instance")
        }
    }
}
