// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appStoreVersionExperiments: AppStoreVersionExperiments {
        AppStoreVersionExperiments(path: path + "/appStoreVersionExperiments")
    }

    public struct AppStoreVersionExperiments {
        /// Path: `/v1/appStoreVersionExperiments`
        public let path: String

        public func post(_ body: AppStoreVersionExperimentCreateRequest) -> Request<AppStoreVersionExperimentResponse> {
            Request(path: path, method: "POST", body: body, id: "appStoreVersionExperiments-create_instance")
        }
    }
}
