// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionOfferCodeOneTimeUseCodes: SubscriptionOfferCodeOneTimeUseCodes {
        SubscriptionOfferCodeOneTimeUseCodes(path: path + "/subscriptionOfferCodeOneTimeUseCodes")
    }

    public struct SubscriptionOfferCodeOneTimeUseCodes {
        /// Path: `/v1/subscriptionOfferCodeOneTimeUseCodes`
        public let path: String
    }
}
