// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var promotedPurchaseImages: PromotedPurchaseImages {
        PromotedPurchaseImages(path: path + "/promotedPurchaseImages")
    }

    public struct PromotedPurchaseImages {
        /// Path: `/v1/promotedPurchaseImages`
        public let path: String

        public func post(_ body: PromotedPurchaseImageCreateRequest) -> Request<PromotedPurchaseImageResponse> {
            Request(path: path, method: "POST", body: body, id: "promotedPurchaseImages-create_instance")
        }
    }
}
