// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var ciBuildRuns: CiBuildRuns {
        CiBuildRuns(path: path + "/ciBuildRuns")
    }

    public struct CiBuildRuns {
        /// Path: `/v1/ciBuildRuns`
        public let path: String

        public func post(_ body: CiBuildRunCreateRequest) -> Request<CiBuildRunResponse> {
            Request(path: path, method: "POST", body: body, id: "ciBuildRuns-create_instance")
        }
    }
}
