// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var ciWorkflows: CiWorkflows {
        CiWorkflows(path: path + "/ciWorkflows")
    }

    public struct CiWorkflows {
        /// Path: `/v1/ciWorkflows`
        public let path: String

        public func post(_ body: CiWorkflowCreateRequest) -> Request<CiWorkflowResponse> {
            Request(path: path, method: "POST", body: body, id: "ciWorkflows-create_instance")
        }
    }
}
