// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appClipDefaultExperiences: AppClipDefaultExperiences {
        AppClipDefaultExperiences(path: path + "/appClipDefaultExperiences")
    }

    public struct AppClipDefaultExperiences {
        /// Path: `/v1/appClipDefaultExperiences`
        public let path: String

        public func post(_ body: AppClipDefaultExperienceCreateRequest) -> Request<AppClipDefaultExperienceResponse> {
            Request(path: path, method: "POST", body: body, id: "appClipDefaultExperiences-create_instance")
        }
    }
}
