// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appScreenshotSets: AppScreenshotSets {
        AppScreenshotSets(path: path + "/appScreenshotSets")
    }

    public struct AppScreenshotSets {
        /// Path: `/v1/appScreenshotSets`
        public let path: String

        public func post(_ body: AppScreenshotSetCreateRequest) -> Request<AppScreenshotSetResponse> {
            Request(path: path, method: "POST", body: body, id: "appScreenshotSets-create_instance")
        }
    }
}
