// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var betaAppClipInvocationLocalizations: BetaAppClipInvocationLocalizations {
        BetaAppClipInvocationLocalizations(path: path + "/betaAppClipInvocationLocalizations")
    }

    public struct BetaAppClipInvocationLocalizations {
        /// Path: `/v1/betaAppClipInvocationLocalizations`
        public let path: String

        public func post(_ body: BetaAppClipInvocationLocalizationCreateRequest) -> Request<BetaAppClipInvocationLocalizationResponse> {
            Request(path: path, method: "POST", body: body, id: "betaAppClipInvocationLocalizations-create_instance")
        }
    }
}
