// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1.Builds.WithID.Relationships {
    public var appEncryptionDeclaration: AppEncryptionDeclaration {
        AppEncryptionDeclaration(path: path + "/appEncryptionDeclaration")
    }

    public struct AppEncryptionDeclaration {
        /// Path: `/v1/builds/{id}/relationships/appEncryptionDeclaration`
        public let path: String

        public var get: Request<BuildAppEncryptionDeclarationLinkageResponse> {
            Request(path: path, method: "GET", id: "builds-appEncryptionDeclaration-get_to_one_relationship")
        }

        public func patch(_ body: BuildAppEncryptionDeclarationLinkageRequest) -> Request<Void> {
            Request(path: path, method: "PATCH", body: body, id: "builds-appEncryptionDeclaration-update_to_one_relationship")
        }
    }
}
