// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appClipAdvancedExperiences: AppClipAdvancedExperiences {
        AppClipAdvancedExperiences(path: path + "/appClipAdvancedExperiences")
    }

    public struct AppClipAdvancedExperiences {
        /// Path: `/v1/appClipAdvancedExperiences`
        public let path: String

        public func post(_ body: AppClipAdvancedExperienceCreateRequest) -> Request<AppClipAdvancedExperienceResponse> {
            Request(path: path, method: "POST", body: body, id: "appClipAdvancedExperiences-create_instance")
        }
    }
}
