// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths {
    public static var v1: V1 {
        V1(path: "https://api.appstoreconnect.apple.com/v1")
    }

    public struct V1 {
        /// Path: `/v1`
        public let path: String
    }
}
