// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var inAppPurchaseAvailabilities: InAppPurchaseAvailabilities {
        InAppPurchaseAvailabilities(path: path + "/inAppPurchaseAvailabilities")
    }

    public struct InAppPurchaseAvailabilities {
        /// Path: `/v1/inAppPurchaseAvailabilities`
        public let path: String

        public func post(_ body: InAppPurchaseAvailabilityCreateRequest) -> Request<InAppPurchaseAvailabilityResponse> {
            Request(path: path, method: "POST", body: body, id: "inAppPurchaseAvailabilities-create_instance")
        }
    }
}
