// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V2 {
    public var inAppPurchases: InAppPurchases {
        InAppPurchases(path: path + "/inAppPurchases")
    }

    public struct InAppPurchases {
        /// Path: `/v2/inAppPurchases`
        public let path: String

        public func post(_ body: InAppPurchaseV2CreateRequest) -> Request<InAppPurchaseV2Response> {
            Request(path: path, method: "POST", body: body, id: "inAppPurchases-create_instance")
        }
    }
}
