// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionAvailabilities: SubscriptionAvailabilities {
        SubscriptionAvailabilities(path: path + "/subscriptionAvailabilities")
    }

    public struct SubscriptionAvailabilities {
        /// Path: `/v1/subscriptionAvailabilities`
        public let path: String

        public func post(_ body: SubscriptionAvailabilityCreateRequest) -> Request<SubscriptionAvailabilityResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionAvailabilities-create_instance")
        }
    }
}
