// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var subscriptionAppStoreReviewScreenshots: SubscriptionAppStoreReviewScreenshots {
        SubscriptionAppStoreReviewScreenshots(path: path + "/subscriptionAppStoreReviewScreenshots")
    }

    public struct SubscriptionAppStoreReviewScreenshots {
        /// Path: `/v1/subscriptionAppStoreReviewScreenshots`
        public let path: String

        public func post(_ body: SubscriptionAppStoreReviewScreenshotCreateRequest) -> Request<SubscriptionAppStoreReviewScreenshotResponse> {
            Request(path: path, method: "POST", body: body, id: "subscriptionAppStoreReviewScreenshots-create_instance")
        }
    }
}
