// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V2 {
    public var sandboxTestersClearPurchaseHistoryRequest: SandboxTestersClearPurchaseHistoryRequest {
        SandboxTestersClearPurchaseHistoryRequest(path: path + "/sandboxTestersClearPurchaseHistoryRequest")
    }

    public struct SandboxTestersClearPurchaseHistoryRequest {
        /// Path: `/v2/sandboxTestersClearPurchaseHistoryRequest`
        public let path: String

        public func post(_ body: SandboxTestersClearPurchaseHistoryRequestV2CreateRequest) -> Request<SandboxTestersClearPurchaseHistoryRequestV2Response> {
            Request(path: path, method: "POST", body: body, id: "sandboxTestersClearPurchaseHistoryRequest-create_instance")
        }
    }
}
