// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1.AppStoreVersions.WithID.Relationships {
    public var appClipDefaultExperience: AppClipDefaultExperience {
        AppClipDefaultExperience(path: path + "/appClipDefaultExperience")
    }

    public struct AppClipDefaultExperience {
        /// Path: `/v1/appStoreVersions/{id}/relationships/appClipDefaultExperience`
        public let path: String

        public var get: Request<AppStoreVersionAppClipDefaultExperienceLinkageResponse> {
            Request(path: path, method: "GET", id: "appStoreVersions-appClipDefaultExperience-get_to_one_relationship")
        }

        public func patch(_ body: AppStoreVersionAppClipDefaultExperienceLinkageRequest) -> Request<Void> {
            Request(path: path, method: "PATCH", body: body, id: "appStoreVersions-appClipDefaultExperience-update_to_one_relationship")
        }
    }
}
