// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appStoreVersionExperimentTreatmentLocalizations: AppStoreVersionExperimentTreatmentLocalizations {
        AppStoreVersionExperimentTreatmentLocalizations(path: path + "/appStoreVersionExperimentTreatmentLocalizations")
    }

    public struct AppStoreVersionExperimentTreatmentLocalizations {
        /// Path: `/v1/appStoreVersionExperimentTreatmentLocalizations`
        public let path: String

        public func post(_ body: AppStoreVersionExperimentTreatmentLocalizationCreateRequest) -> Request<AppStoreVersionExperimentTreatmentLocalizationResponse> {
            Request(path: path, method: "POST", body: body, id: "appStoreVersionExperimentTreatmentLocalizations-create_instance")
        }
    }
}
