// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import URLQueryEncoder

extension Paths.V1 {
    public var appClips: AppClips {
        AppClips(path: path + "/appClips")
    }

    public struct AppClips {
        /// Path: `/v1/appClips`
        public let path: String
    }
}
